-- MySQL Script generated by MySQL Workbench
-- Sun Apr  7 21:02:14 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Patient` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `dateOfBirth` DATETIME NOT NULL,
  `phoneNumber` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `mailingAddress` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Dentist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Dentist` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `phoneNumber` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Surgery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Surgery` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `locationAddress` VARCHAR(255) NULL,
  `phoneNumber` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Appointment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Appointment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dateAppointment` DATETIME NOT NULL,
  `Patient_id` INT NOT NULL,
  `Dentist_id` INT NOT NULL,
  `Surgery_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Patient_id`, `Dentist_id`, `Surgery_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Appointment_Patient_idx` (`Patient_id` ASC) VISIBLE,
  INDEX `fk_Appointment_Dentist1_idx` (`Dentist_id` ASC) VISIBLE,
  INDEX `fk_Appointment_Surgery1_idx` (`Surgery_id` ASC) VISIBLE,
  CONSTRAINT `fk_Appointment_Patient`
    FOREIGN KEY (`Patient_id`)
    REFERENCES `mydb`.`Patient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Appointment_Dentist1`
    FOREIGN KEY (`Dentist_id`)
    REFERENCES `mydb`.`Dentist` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Appointment_Surgery1`
    FOREIGN KEY (`Surgery_id`)
    REFERENCES `mydb`.`Surgery` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Specialization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Specialization` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `Dentist_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Dentist_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Specialization_Dentist1_idx` (`Dentist_id` ASC) VISIBLE,
  CONSTRAINT `fk_Specialization_Dentist1`
    FOREIGN KEY (`Dentist_id`)
    REFERENCES `mydb`.`Dentist` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- -----------------------------------------------------

INSERT INTO `mydb`.`Dentist` (`firstName`, `lastName`, `phoneNumber`, `email`) VALUES ('John', 'Smith', '543-246-9765', 'jhon@email.com');
INSERT INTO `mydb`.`Dentist` (`firstName`, `lastName`, `phoneNumber`, `email`) VALUES ('Sam', 'Jill', '734-890-8787', 'sam@email.com');
INSERT INTO `mydb`.`Dentist` (`firstName`, `lastName`, `phoneNumber`, `email`) VALUES ('George', 'Wall', '876-098-7865', 'geo@email.com');
INSERT INTO `mydb`.`Dentist` (`firstName`, `lastName`, `phoneNumber`, `email`) VALUES ('Adam', 'Grey', '767-989-0987', 'adam@email.com');

INSERT INTO `mydb`.`Patient` (`firstName`, `lastName`, `dateOfBirth`, `phoneNumber`, `email`, `mailingAddress`) VALUES ('Mayra', 'Pullupaxi', '1989-03-11', '641-233-1111', 'mayra@gmail.com', 'RukmapuraPark');
INSERT INTO `mydb`.`Patient` (`firstName`, `lastName`, `dateOfBirth`, `phoneNumber`, `email`, `mailingAddress`) VALUES ('Jim', 'Johnson', '2000-01-01', '656-890-9890', 'jim@gmail.com', '1000 Nth St3');
INSERT INTO `mydb`.`Patient` (`firstName`, `lastName`, `dateOfBirth`, `phoneNumber`, `email`, `mailingAddress`) VALUES ('Carol', 'Saml', '2006-09-24', '767-908-9865', 'carol@gmail.com', 'CC Rd 4th');

INSERT INTO `mydb`.`Surgery` (`id`, `name`, `locationAddress`, `phoneNumber`) VALUES ('1', 'Fairfield ADS', '1000 N 4th St,', '642-909-9878');
INSERT INTO `mydb`.`Surgery` (`id`, `name`, `locationAddress`, `phoneNumber`) VALUES ('2', 'Otummwa ADS', '234 S Rd St', '654-906-6543');
INSERT INTO `mydb`.`Surgery` (`id`, `name`, `locationAddress`, `phoneNumber`) VALUES ('3', 'Des Moines ADS', '1401 Locust St', '234-567-4456');

INSERT INTO `mydb`.`Specialization` (`name`, `Dentist_id`) VALUES ('Dental anesthesiology', '1');
INSERT INTO `mydb`.`Specialization` (`name`, `Dentist_id`) VALUES ('Endodontics', '2');
INSERT INTO `mydb`.`Specialization` (`name`, `Dentist_id`) VALUES ('Oral and maxillofacial pathology', '3');
INSERT INTO `mydb`.`Specialization` (`name`, `Dentist_id`) VALUES ('Dental public health ', '4');

INSERT INTO `mydb`.`Appointment` (`dateAppointment`, `Patient_id`, `Dentist_id`, `Surgery_id`) VALUES ('2024-04-06 10:00:00', '3', '2', '3');
INSERT INTO `mydb`.`Appointment` (`dateAppointment`, `Patient_id`, `Dentist_id`, `Surgery_id`) VALUES ('2024-04-07 15:00:00', '2', '2', '2');
INSERT INTO `mydb`.`Appointment` (`dateAppointment`, `Patient_id`, `Dentist_id`, `Surgery_id`) VALUES ('2024-04-06 13:00:00', '3', '3', '3');
INSERT INTO `mydb`.`Appointment` (`dateAppointment`, `Patient_id`, `Dentist_id`, `Surgery_id`) VALUES ('2024-04-10 11:00:00', '4', '4', '1');

-- -----------------------------------------------------
-- -----------------------------------------------------

SELECT * FROM mydb.Dentist
order by lastName ASC;

-- -----------------------------------------------------
-- -----------------------------------------------------

SELECT a.id, a.dateAppointment, p.*
FROM Appointment a join Patient p
on a.Patient_id = p.id
where a.Dentist_id = 2;

-- -----------------------------------------------------
-- -----------------------------------------------------

SELECT a.*
FROM Appointment a join Surgery s
on a.Surgery_id = s.id
where s.name = 'Des Moines ADS';

-- -----------------------------------------------------
-- -----------------------------------------------------

SELECT a.* FROM Appointment a join Patient p
on a.Patient_id = p.id
where p.id = 3
and CAST(a.dateAppointment as DATE) = '2024-04-06';
