version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8081:8080
    networks:
      - springboot-app-ads
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/cs489-dentalsurgery-db2
    depends_on:
      - mysqldb

    volumes:
      - .m2:/root/.m2

  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3307:3306
    networks:
      - springboot-app-ads
    environment:
      MYSQL_DATABASE: cs489-dentalsurgery-db2
      MYSQL_USER: dentalsurgery
      MYSQL_PASSWORD: test1234
      MYSQL_ROOT_PASSWORD: test1234

networks:
  springboot-app-ads: