# Using OpenJDK version 17 as the base image
FROM openjdk:17

COPY target/dentalsurgeryapp-0.0.1-SNAPSHOT.jar dentalsurgeryapp-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java", "-jar", "/dentalsurgeryapp-0.0.1-SNAPSHOT.jar"]